"""
color_overrides.py
Standalone color override mapping — no external dependencies.
(model_key_lowercase, color_en_lowercase) → official_color
"""

OVERRIDES: dict[tuple[str, str], str] = {
    # 11
    ("11", "black"): "Black",
    ("11", "green"): "Green",
    ("11", "purple"): "Purple",
    ("11", "red"): "(PRODUCT) RED",
    ("11", "white"): "White",
    ("11", "yellow"): "Yellow",
    # 12
    ("12", "black"): "Black",
    ("12", "blue"): "Blue",
    ("12", "green"): "Green",
    ("12", "purple"): "Purple",
    ("12", "red"): "(PRODUCT) RED",
    ("12", "white"): "White",
    # 12 Mini
    ("12 mini", "black"): "Black",
    ("12 mini", "blue"): "Blue",
    ("12 mini", "green"): "Green",
    ("12 mini", "purple"): "Purple",
    ("12 mini", "red"): "(PRODUCT) RED",
    ("12 mini", "white"): "White",
    # 13
    ("13", "alpine green"): "Green",
    ("13", "black"): "Midnight",
    ("13", "blue"): "Blue",
    ("13", "green"): "Green",
    ("13", "midnight"): "Midnight",
    ("13", "pink"): "Pink",
    ("13", "red"): "(PRODUCT) RED",
    ("13", "starlight"): "Starlight",
    ("13", "white"): "Starlight",
    # 13 Mini
    ("13 mini", "black"): "Midnight",
    ("13 mini", "blue"): "Blue",
    ("13 mini", "green"): "Green",
    ("13 mini", "midnight"): "Midnight",
    ("13 mini", "pink"): "Pink",
    ("13 mini", "red"): "(PRODUCT) RED",
    ("13 mini", "starlight"): "Starlight",
    ("13 mini", "white"): "Starlight",
    # 13 Pro
    ("13 pro", "alpine green"): "Alpine Green",
    ("13 pro", "black"): "Graphite",
    ("13 pro", "gold"): "Gold",
    ("13 pro", "graphite"): "Graphite",
    ("13 pro", "sierra blue"): "Sierra Blue",
    ("13 pro", "silver"): "Silver",
    # 13 Pro Max
    ("13 pro max", "alpine green"): "Alpine Green",
    ("13 pro max", "black"): "Graphite",
    ("13 pro max", "gold"): "Gold",
    ("13 pro max", "graphite"): "Graphite",
    ("13 pro max", "sierra blue"): "Sierra Blue",
    ("13 pro max", "silver"): "Silver",
    # 14
    ("14", "blue"): "Blue",
    ("14", "deep purple"): "Purple",
    ("14", "black"): "Midnight",
    ("14", "midnight"): "Midnight",
    ("14", "purple"): "Purple",
    ("14", "red"): "(PRODUCT) RED",
    ("14", "starlight"): "Starlight",
    ("14", "white"): "Starlight",
    ("14", "yellow"): "Yellow",
    # 14 Plus
    ("14 plus", "black"): "Midnight",
    ("14 plus", "blue"): "Blue",
    ("14 plus", "midnight"): "Midnight",
    ("14 plus", "purple"): "Purple",
    ("14 plus", "red"): "(PRODUCT) RED",
    ("14 plus", "starlight"): "Starlight",
    ("14 plus", "white"): "Starlight",
    ("14 plus", "yellow"): "Yellow",
    # 14 Pro
    ("14 pro", "black"): "Space Black",
    ("14 pro", "deep purple"): "Deep Purple",
    ("14 pro", "gold"): "Gold",
    ("14 pro", "purple"): "Deep Purple",
    ("14 pro", "silver"): "Silver",
    ("14 pro", "space black"): "Space Black",
    ("14 pro", "white"): "Silver",
    # 14 Pro Max
    ("14 pro max", "black"): "Space Black",
    ("14 pro max", "deep purple"): "Deep Purple",
    ("14 pro max", "gold"): "Gold",
    ("14 pro max", "purple"): "Deep Purple",
    ("14 pro max", "silver"): "Silver",
    ("14 pro max", "space black"): "Space Black",
    ("14 pro max", "white"): "Silver",
    # 15
    ("15", "red"): "Pink",
    ("15", "white"): "Blue",
    ("15", "purple"): "Pink",
    ("15", "black"): "Black",
    ("15", "blue"): "Blue",
    ("15", "green"): "Green",
    ("15", "pink"): "Pink",
    ("15", "yellow"): "Yellow",
    # 15 Plus
    ("15 plus", "black"): "Black",
    ("15 plus", "blue"): "Blue",
    ("15 plus", "green"): "Green",
    ("15 plus", "pink"): "Pink",
    ("15 plus", "white"): "Blue",
    ("15 plus", "purple"): "Pink",
    ("15 plus", "red"): "Pink",
    ("15 plus", "yellow"): "Yellow",
    # 15 Pro
    ("15 pro", "black"): "Black Titanium",
    ("15 pro", "blue"): "Blue Titanium",
    ("15 pro", "natural"): "Natural Titanium",
    ("15 pro", "white"): "White Titanium",
    ("15 pro", "gold"): "Natural Titanium",
    ("15 pro", "purple"): "Blue Titanium",
    # 15 Pro Max
    ("15 pro max", "black"): "Black Titanium",
    ("15 pro max", "blue"): "Blue Titanium",
    ("15 pro max", "blue titanium"): "Blue Titanium",
    ("15 pro max", "natural"): "Natural Titanium",
    ("15 pro max", "natural titanium"): "Natural Titanium",
    ("15 pro max", "white"): "White Titanium",
    ("15 pro max", "white titanium"): "White Titanium",
    ("15 pro max", "gold"): "Natural Titanium",
    ("15 pro max", "purple"): "Blue Titanium",
    # 16
    ("16", "black"): "Black",
    ("16", "pink"): "Pink",
    ("16", "teal"): "Teal",
    ("16", "ultramarine"): "Ultramarine",
    ("16", "white"): "White",
    # 16 Plus
    ("16 plus", "black"): "Black",
    ("16 plus", "pink"): "Pink",
    ("16 plus", "teal"): "Teal",
    ("16 plus", "ultramarine"): "Ultramarine",
    ("16 plus", "white"): "White",
    # 16 Pro
    ("16 pro", "black"): "Black Titanium",
    ("16 pro", "desert"): "Desert Titanium",
    ("16 pro", "natural"): "Natural Titanium",
    ("16 pro", "white"): "White Titanium",
    # 16 Pro Max
    ("16 pro max", "black"): "Black Titanium",
    ("16 pro max", "desert"): "Desert Titanium",
    ("16 pro max", "natural"): "Natural Titanium",
    ("16 pro max", "white"): "White Titanium",
    # 16E
    ("16e", "black"): "Black",
    ("16e", "white"): "White",
    # 17
    ("17", "black"): "Black",
    ("17", "blue"): "Mist Blue",
    ("17", "mist blue"): "Mist Blue",
    ("17", "lavender"): "Lavender",
    ("17", "sage"): "Sage",
    ("17", "white"): "White",
    # 17 Air
    ("17 air", "black"): "Space Black",
    ("17 air", "blue"): "Sky Blue",
    ("17 air", "cloud white"): "Cloud White",
    ("17 air", "gold"): "Light Gold",
    ("17 air", "light gold"): "Light Gold",
    ("17 air", "sky blue"): "Sky Blue",
    ("17 air", "space black"): "Space Black",
    ("17 air", "white"): "Cloud White",
    # 17 Pro
    ("17 pro", "blue"): "Deep Blue",
    ("17 pro", "orange"): "Cosmic Orange",
    ("17 pro", "cosmic orange"): "Cosmic Orange",
    ("17 pro", "silver"): "Silver",
    # 17 Pro Max
    ("17 pro max", "blue"): "Deep Blue",
    ("17 pro max", "orange"): "Cosmic Orange",
    ("17 pro max", "cosmic orange"): "Cosmic Orange",
    ("17 pro max", "silver"): "Silver",
    # 17E
    ("17e", "black"): "Black",
    ("17e", "pink"): "Soft Pink",
    ("17e", "white"): "White",
    # SE (1st gen)
    ("se", "black"): "Space Gray",
    ("se", "red"): "(PRODUCT) RED",
    ("se", "white"): "Silver",
    # SE 2
    ("se 2", "black"): "Black",
    ("se 2", "red"): "(PRODUCT) RED",
    ("se 2", "white"): "White",
    # SE 3
    ("se 3", "black"): "Midnight",
    ("se 3", "red"): "(PRODUCT) RED",
    ("se 3", "white"): "Starlight",
    # XR
    ("xr", "black"): "Black",
    ("xr", "red"): "(PRODUCT) RED",
}